# Generated by Django 5.1.1 on 2024-10-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
